### ISSUE TITLE
Multiple Page Issues/Typos/Ideas

### ISSUE THREAD

**Issue by Dns-q** [ShadowNode/shadownode.github.io#72]
- On new wiki landing pages(with small buttons), logo picture still opening full screen image view.
- All external text links should open in separate window/tab. And same for links to webstore 
- Banned item list Chunkloaders have a link that goes to 404
- Crash Reports section. Maybe switch from pastebin to https://mclo.gs
   - In line `Paste the content of the latest crash-report on <site>` site is not a link (same with many other "Copy" boxes on that page)
-  Crates page table is very narrow. Would look better if it was item name per 1 line, maybe with some more separation. What is [Image](https://prnt.sc/26ebhdp "CratesImage")
- Add page with recommeneded Java Parameters, where players can copy them
- Webstore page banner is missing and its link directs to invalid (www) page

**Comment by MatthewM** [comment]
The wiki landing pages issue has already been fixed and can be tested [here](https://deploy-preview-71--romantic-wing-7b1cfa.netlify.app/home/). Please let me know if you still have the same issue.

I can't tell what the image is - can you try linking again?

I'll look into the rest of the issues, however, the problem I'll note is that those tables are in markdown and it's fully the way that the backend is parsing them.

**Comment by MatthewM** [comment]
I've added the requested features at this time. Sadly, we're not able to change the crates table from what I can see without making the page not friendly to edit.

I'm not sure how I  feel about the [Java args page for the current PR](https://deploy-preview-71--romantic-wing-7b1cfa.netlify.app/home/guides/java-args/). So if you have different args that you want includes please let me know.
